M48
; DRILL file {KiCad 6.0.9-8da3e8f707~116~ubuntu20.04.1} date sob 17 dec 2022 22:05:44
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-17T22:05:44+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
%
G90
G05
T1
X109.525Y-137.16
X116.525Y-137.16
T0
M30
